
from aiogram.types import ReplyKeyboardMarkup, KeyboardButton
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton


keyboard_2 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
keyboard_3 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
keyboard_4 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
keyboard_5 = ReplyKeyboardMarkup(resize_keyboard=True, one_time_keyboard=True)
keyboard_6 = InlineKeyboardMarkup()
keyboard_7 = InlineKeyboardMarkup()
                   
btn_2_E = KeyboardButton('Привет')                   
btn_3_E = KeyboardButton('Привет')                   
btn_3_F = KeyboardButton('спасибо')                   
btn_4_E = KeyboardButton('Привет')                   
btn_4_F = KeyboardButton('спасибо')                   
btn_4_G = KeyboardButton('кнопка 3')                   
btn_5_E = KeyboardButton('Привет')                   
btn_5_F = KeyboardButton('спасибо')                   
btn_5_G = KeyboardButton('кнопка 3')                   
btn_5_H = KeyboardButton('Кнопка 4')                   
btn_6_E = InlineKeyboardButton(text='Кнопка 1', callback_data='data_1')                   
btn_6_F = InlineKeyboardButton(text='Кнопка 2', callback_data='data_2')                   
btn_7_E = InlineKeyboardButton(text='Кнопка 3', callback_data='data_3')                   
btn_7_F = InlineKeyboardButton(text='Кнопка 4', callback_data='data_4')
    
keyboard_2.add(btn_2_E)    
keyboard_3.add(btn_3_E)    
keyboard_3.add(btn_3_F)    
keyboard_4.add(btn_4_E)    
keyboard_4.add(btn_4_F)    
keyboard_4.add(btn_4_G)    
keyboard_5.add(btn_5_E)    
keyboard_5.add(btn_5_F)    
keyboard_5.add(btn_5_G)    
keyboard_5.add(btn_5_H)    
keyboard_6.add(btn_6_E)    
keyboard_6.add(btn_6_F)    
keyboard_7.add(btn_7_E)    
keyboard_7.add(btn_7_F)